version: '3.9'

services:
    dbpostgresql:
        image: postgres:15-alpine
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
        volumes:
            - db_postgresql:/var/lib/postgresql/data
        container_name: dbpostgresql
        networks:
            - family-network
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "Postgres2022!"

    message.broker.rabbitmq:
        build: ./infra/rabbitmq/
        container_name: messagebrokerrabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - family-network

    redis:
        image: redis:6.2-alpine
        container_name: redis
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
        networks:
            - family-network
        ports:
            - '6379:6379'
        volumes: 
            - cache:/data

    familyaccountsapi:
        build:
            context: ./family.accounts.api
            dockerfile: Dockerfile
        container_name: family-accounts-api
        ports:
            - "9501:8080"
        networks: 
            - family-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis

    fileuploadapi:
        build:
            context: ./family.file.api
            dockerfile: Dockerfile
        container_name: family-file-api
        ports:
            - "9502:8080"
        networks: 
            - family-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - uploads:/app/Uploads

    familyaccountsloginweb:
        build:
            context: ./family.accounts.login.web
            dockerfile: Dockerfile
        container_name: family.accounts.login.web
        ports:
            - "9001:8080"
        networks: 
            - family-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
            - familyaccountsapi

    familyaccountsmanagementweb:
        build:
            context: ./family.accounts.management.web
            dockerfile: Dockerfile
        container_name: family.accounts.management.web
        ports:
            - "9002:8080"
        networks: 
            - family-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
            - familyaccountsloginweb

volumes:
    cache:
        driver: local
    uploads:
        driver: local
    db_postgresql:
        driver: local
        
networks:
  family-network:
    driver: bridge