version: '3.9'

services:
    dbpostgresql:
        image: postgres:15-alpine
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
        volumes:
            - db_postgresql:/var/lib/postgresql/data
        container_name: dbpostgresql
        networks:
            - team-network
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "Postgres2022!"

    message.broker.rabbitmq:
        build: ./infra/rabbitmq/
        container_name: messagebrokerrabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - team-network

    redis:
        image: redis:6.2-alpine
        container_name: redis
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
        networks:
            - team-network
        ports:
            - '6379:6379'
        volumes: 
            - cache:/data

    teamaccountsapi:
        build:
            context: ./team.accounts.api
            dockerfile: Dockerfile
        container_name: team-accounts-api
        ports:
            - "9501:8080"
        networks: 
            - team-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis

    fileuploadapi:
        build:
            context: ./team.file.api
            dockerfile: Dockerfile
        container_name: team-file-api
        ports:
            - "9502:8080"
        networks: 
            - team-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - uploads:/app/Uploads
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
    teamapi:
        build:
            context: ./team.api
            dockerfile: Dockerfile
        container_name: team-api
        ports:
            - "9503:8080"
        networks: 
            - team-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - uploads:/app/Uploads
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis

    teamaccountsloginweb:
        build:
            context: ./team.accounts.login.web
            dockerfile: Dockerfile
        container_name: team.accounts.login.web
        ports:
            - "9001:8080"
        networks: 
            - team-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
            - teamaccountsapi

    teamaccountsmanagementweb:
        build:
            context: ./team.accounts.management.web
            dockerfile: Dockerfile
        container_name: team.accounts.management.web
        ports:
            - "9002:8080"
        networks: 
            - team-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
            - teamaccountsloginweb

volumes:
    cache:
        driver: local
    uploads:
        driver: local
    db_postgresql:
        driver: local
        
networks:
  team-network:
    driver: bridge